import fs from 'node:fs/promises';
import path from 'node:path';
import { TestIntent } from '../core/types.js';
import { createModelClient } from '../generator/modelClient.js';
import { Project } from '../projects/types.js';
import { listStories } from '../stories/store.js';
import { StoryStatus } from '../stories/types.js';

const STATUS_BADGE: Record<StoryStatus, string> = {
  passing: '✅ passing',
  failing: '⚠️ failing',
  'needs-review': '⚠️ needs review',
  generated: '◷ generated',
  new: '◷ new'
};

export interface FlowDoc {
  storyId: string;
  title: string;
  status: StoryStatus;
  source: string;
  testRef: string;
  instructions: string;
  steps: string[];
}

export interface DocsModel {
  project: { id: string; name: string; baseUrl: string };
  flows: FlowDoc[];
}

export interface DocsResult {
  indexPath: string;
  flowCount: number;
}

/**
 * Build the structured living-docs model for a project: one flow per story, with
 * derived steps and a status tied to the flow's test. Shared by the markdown
 * writer (generateDocs) and the dashboard's docs API so they never drift.
 */
export async function buildDocsModel(project: Project): Promise<DocsModel> {
  const stories = await listStories(project.id);
  const client = createModelClient('mock');
  const flows: FlowDoc[] = [];
  for (const story of stories) {
    const intent = await client.parseSpec(story.body);
    flows.push({
      storyId: story.id,
      title: story.title,
      status: story.status,
      source: story.source,
      testRef: `${project.testsDir.split(path.sep).join('/')}/${story.id}.spec.ts`,
      instructions: story.body.trim(),
      steps: deriveSteps(intent)
    });
  }
  return { project: { id: project.id, name: project.name, baseUrl: project.baseUrl }, flows };
}

/** Write living documentation (index + per-flow markdown) into the project's docs dir. */
export async function generateDocs(project: Project): Promise<DocsResult> {
  const model = await buildDocsModel(project);
  const outDir = path.join(project.repoPath, project.docsDir, 'testpilot');
  await fs.mkdir(outDir, { recursive: true });

  const rows: string[] = [];
  for (const flow of model.flows) {
    await fs.writeFile(path.join(outDir, `${flow.storyId}.md`), flowMarkdown(flow), 'utf8');
    rows.push(`| ${escapePipe(flow.title)} | ${STATUS_BADGE[flow.status]} | \`${flow.testRef}\` | [doc](./${flow.storyId}.md) |`);
  }

  const index = [
    `# ${project.name} — Test Documentation`,
    '',
    '_Living documentation generated by testpilot from natural-language stories and the tests they produced._',
    `Base URL: \`${project.baseUrl}\``,
    '',
    rows.length
      ? ['| Flow | Status | Test | Doc |', '|---|---|---|---|', ...rows].join('\n')
      : '_No stories yet for this project._',
    '',
    '> Every flow is backed by an automated test. A failing status flags documentation that no longer matches the product.',
    ''
  ].join('\n');
  const indexPath = path.join(outDir, 'index.md');
  await fs.writeFile(indexPath, index, 'utf8');
  return { indexPath, flowCount: model.flows.length };
}

export function statusBadge(status: StoryStatus): string {
  return STATUS_BADGE[status];
}

function deriveSteps(intent: TestIntent): string[] {
  return [
    `Navigate to ${intent.route}`,
    intent.credentials ? `Enter credentials (${intent.credentials.email})` : '',
    `Click the submit control ("${intent.submitText}")`,
    `Expect to reach ${intent.expectedPath} with "${intent.expectedText}" visible`
  ].filter((step) => step !== '');
}

function flowMarkdown(flow: FlowDoc): string {
  return (
    [
      `# ${flow.title}`,
      '',
      `**Status:** ${STATUS_BADGE[flow.status]} · backed by \`${flow.testRef}\``,
      `**Source:** ${flow.source}`,
      '',
      '## Instructions',
      '',
      flow.instructions,
      '',
      '## Flow',
      '',
      ...flow.steps.map((step, index) => `${index + 1}. ${step}`),
      '',
      '_This page is backed by an automated test; if the test fails, this flow is flagged for review._',
      ''
    ].join('\n')
  );
}

function escapePipe(value: string): string {
  return value.replace(/\|/g, '\\|');
}
