import fs from 'node:fs/promises';
import path from 'node:path';
import { TestIntent } from '../core/types.js';
import { createModelClient } from '../generator/modelClient.js';
import { Project } from '../projects/types.js';
import { listStories } from '../stories/store.js';
import { Story, StoryStatus } from '../stories/types.js';

const STATUS_BADGE: Record<StoryStatus, string> = {
  passing: '✅ passing',
  failing: '⚠️ failing',
  'needs-review': '⚠️ needs review',
  generated: '◷ generated',
  new: '◷ new'
};

export interface DocsResult {
  indexPath: string;
  flowCount: number;
}

/**
 * Living documentation: for each story, write a flow doc (instructions + derived
 * steps + status) backed by its test, plus an index. Because each flow is tied to
 * a test, a failing status flags docs that no longer match the product.
 */
export async function generateDocs(project: Project): Promise<DocsResult> {
  const stories = await listStories(project.id);
  const client = createModelClient('mock');
  const outDir = path.join(project.repoPath, project.docsDir, 'testpilot');
  await fs.mkdir(outDir, { recursive: true });

  const rows: string[] = [];
  for (const story of stories) {
    const intent = await client.parseSpec(story.body);
    const flowFile = `${story.id}.md`;
    const testRef = `${project.testsDir.split(path.sep).join('/')}/${story.id}.spec.ts`;
    await fs.writeFile(path.join(outDir, flowFile), flowDoc(story, intent, testRef), 'utf8');
    rows.push(`| ${escapePipe(story.title)} | ${STATUS_BADGE[story.status]} | \`${testRef}\` | [doc](./${flowFile}) |`);
  }

  const index = [
    `# ${project.name} — Test Documentation`,
    '',
    '_Living documentation generated by testpilot from natural-language stories and the tests they produced._',
    `Base URL: \`${project.baseUrl}\``,
    '',
    rows.length
      ? ['| Flow | Status | Test | Doc |', '|---|---|---|---|', ...rows].join('\n')
      : '_No stories yet for this project._',
    '',
    '> Every flow is backed by an automated test. A failing status flags documentation that no longer matches the product.',
    ''
  ].join('\n');
  const indexPath = path.join(outDir, 'index.md');
  await fs.writeFile(indexPath, index, 'utf8');
  return { indexPath, flowCount: stories.length };
}

function flowDoc(story: Story, intent: TestIntent, testRef: string): string {
  return (
    [
      `# ${story.title}`,
      '',
      `**Status:** ${STATUS_BADGE[story.status]} · backed by \`${testRef}\``,
      `**Source:** ${story.source}${story.externalId ? ` ${story.externalId}` : ''}`,
      '',
      '## Instructions',
      '',
      story.body.trim(),
      '',
      '## Flow',
      '',
      `1. Navigate to \`${intent.route}\``,
      intent.credentials ? `2. Enter credentials (\`${intent.credentials.email}\`)` : '',
      `3. Click the submit control ("${intent.submitText}")`,
      `4. Expect to reach \`${intent.expectedPath}\` with "${intent.expectedText}" visible`,
      '',
      '_This page is backed by an automated test; if the test fails, this flow is flagged for review._',
      ''
    ]
      .filter((line) => line !== '')
      .join('\n') + '\n'
  );
}

function escapePipe(value: string): string {
  return value.replace(/\|/g, '\\|');
}
